### PR TITLE
Fix for Promise\settle()

### LINKED ISSUE #49: Promise\settle() is not working properly
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | guzzlehttp/guzzle                  6.3.3  guzzlehttp/promises                v1.3.1 guzzlehttp/psr7                    1.4.2 php-http/guzzle6-adapter           v1.1.1

#### Actual Behavior
If the first HTTP call (promise) returns HTTP >= 400 (which triggers and exception in Guzzle by default) then the adapter throws the exception for the first HTTP call instead it would return the result of all promises.

```php
<?php

require_once "vendor/autoload.php";

use GuzzleHttp\Client;
use GuzzleHttp\Promise;
use GuzzleHttp\Psr7\Request;


$client = new Client(['base_uri' => 'http://httpbin.org/']);

$pluginClient = new \Http\Client\Common\PluginClient(
  new Http\Adapter\Guzzle6\Client($client), []
);


// Initiate each request but do not block
$promises = [
  'image' => $pluginClient->sendAsyncRequest(new Request('GET', 'status/404')),
  'png'   => $pluginClient->sendAsyncRequest(new Request('GET', 'status/200')),
  'jpeg'  => $pluginClient->sendAsyncRequest(new Request('GET', 'status/200')),
  'webp'  => $pluginClient->sendAsyncRequest(new Request('GET', 'status/404'))
];

try {
  // Wait for the requests to complete, even if some of them fail
  $results = Promise\settle($promises)->wait();
}
catch (\Exception $e) {
  echo $e->getMessage();
}
exit(0);

```

#### Expected Behaviour
settle() should "Wait for the requests to complete, even if some of them fail". So even if the first HTTP call returns HTTP >= 400 an exception should not be thrown.

http://docs.guzzlephp.org/en/stable/quickstart.html#concurrent-requests

```php
<?php

require_once "vendor/autoload.php";

use GuzzleHttp\Client;
use GuzzleHttp\Promise;

$client = new Client(['base_uri' => 'http://httpbin.org/']);

// Initiate each request but do not block
$promises = [
  'image' => $client->getAsync('status/404'),
  'png'   => $client->getAsync('status/200'),
  'jpeg'  => $client->getAsync('status/200'),
  'webp'  => $client->getAsync('status/404')
];

try {
  // Wait for the requests to complete, even if some of them fail
  $results = Promise\settle($promises)->wait();
}
catch (\Exception $e) {
  echo $e->getMessage();
}
exit(0);

```

#### Steps to Reproduce

See the code snippets above.

#### Possible Solutions

For the first sight it seems the adapter should also wrap the result of all promises to a Promise object and return that instead of returning the results directly. At least this is what Guzzle Promise's working code indicates for me.
https://github.com/guzzle/promises/blob/v1.3.1/src/Promise.php#L69

### PR DESCRIPTION
**Pull request by mxr576**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #49 
| Documentation   | -
| License         | MIT

#### What's in this PR?

Possible fix for the issue described in #49.

### CODE REVIEW

**Comment by mxr576** [comment]
Hm, maybe this actually going to be a BC breaking change? o.O

**Comment by Nyholm** [comment]
Thank you for this PR. 

As far as I know, the wait function should return a response or an exception. Why do you think that should change?

**Comment by mxr576** [comment]
@Nyholm Please read #49 for more information about the reasons behind this PR. This is just a possible solution to this problem maybe this is not the best.

`wait()` can return promise as well, return value depends on the value of unwrap. Example from Guzzle Promises: https://github.com/guzzle/promises/blob/v1.3.1/src/Promise.php#L60

**Comment by mxr576** [comment]
Hint, probably there is a difference between how wait() is implemented in php-http/promise and guzzle/promise.

https://github.com/guzzle/promises/blob/v1.3.1/src/PromiseInterface.php#L92

**Comment by mxr576** [comment]
I am closing this PR, because this is clearly not the best solution for addressing this problem. I tried multiple things, but I could not fix this problem. It seems settle() won't work properly until wrapped promise has to be fulfilled in Promise::wrap() because https://github.com/guzzle/promises/blob/v1.3.1/src/Promise.php#L255.
A possible workaround could be disabling http_errors option in Guzzle client and manually transforming >= 400 HTTP codes to exceptions if needed.

**Pull request closed without merging**
