### PR TITLE
Set state to rejected when the rejection callback is called

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@kbond this might solve the return value problem. But in order to test, please revert the previous fix to emulate an unhandleable error.

**Comment by sagikazarmark** [comment]
@joelwurtz shouldn't the promise be rejected, when an exception is thrown? No matter if it's a domain exception or not.

**Comment by kbond** [comment]
I am getting another error now: "Error: Can only throw objects"

**Comment by sagikazarmark** [comment]
LOL

**Comment by kbond** [comment]
In https://github.com/php-http/guzzle6-adapter/blob/master/src/Guzzle6Promise.php#L99 `$this->exception` is null

**Comment by sagikazarmark** [comment]
Ah, of course.

**Comment by sagikazarmark** [comment]
Well, in theory this should do the trick, but we should definitely revise the waiting logic in the promise wrapper.

**Comment by kbond** [comment]
That did the trick.

**Comment by sagikazarmark** [comment]
Merging this for now, but this change could have unpredictable outcomes. I started to implement a test case to cover the most cases.

**Pull request merged**
