### PR TITLE
Rewrote PromiseExceptionTests

### PR DESCRIPTION
**Pull request by gmponos**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

#### What's in this PR?

Rewrote the tests of PromiseExceptionTest class.

#### Why?

- Each test now has each own separate test case.
- Sweetened the syntax/codestyle by using the `class` constant.
- Tests previously where using reflection in order to check a private method. Private methods are not to be tested. Private methods exist as servants of the public methods. In the way it was before it makes the refactoring harder. The reason is that if I change the private function and what it does I must not alter my tests as long as the public function still works as expected.
- Reflection is just slow.
- Used more actual objects instead of mocks. Using actual objects tests even more thorough your application/library.

### CODE REVIEW

**Comment by gmponos** [comment]
Ping @Nyholm since he was the original author of the class.

**Comment by gmponos** [comment]
What! the build fails because of --prefer-lowest and it installs phpunit `4.8.35`. I can do a work around with `try.. catch` around `wait()` but I say we lock this package to `phpunit: ^7.0`

**Comment by dbu** [comment]
yeah, please lock at a modern version of phpunit in require-dev. we don't care about being tested with the oldest possible phpunit ;-)

**Comment by gmponos** [comment]
Done :)

**Comment by dbu** [comment]
i like the change and doing less mocking!

i think the test would be more consise when using a data provider to define the map of guzzle exception to psr exception, as the tests look all very similar. wdyt?

**Comment by gmponos** [comment]
> wdyt

Yes it is better.. we will need two dataproviders one with the tests that have response and one with the ones that do not.. I could do it with a flag and an `if` statement but I don't like having `branches` on tests..

**Comment by dbu** [comment]
yeah, better have 2 providers than two flows in one test.

**Comment by dbu** [comment]
why is this not failing when #62 is not merged yet? are we not covering those cases?

**Comment by gmponos** [comment]
> why is this not failing when #62 is not merged yet? are we not covering those cases?

That's what initiated me rewriting the tests. Yes you are not covering these test cases... but I forgot to add these extra cases 🤦‍♂️ 

Now that I think of it... on current PR we must add these two extra cases and then on #62 we must update the tests accordingly after this gets merged. 

I will mark both PR as WIP.

**Comment by gmponos** [comment]
ping @dbu

**Comment by dbu** [comment]
thanks a lot!

**Comment by sagikazarmark** [comment]
Thanks @gmponos

**Pull request merged**
