### PR TITLE
add support for php 8

### PR DESCRIPTION
**Pull request by dmaicher**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| Documentation   | -
| License         | MIT

#### What's in this PR?

PHP 8 will be released soon. So it would be nice to add support for it.

#### Checklist

- [x] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix

### CODE REVIEW

**Comment by dmaicher** [comment]
The PrettyCI fail seems unrelated?

**Comment by dmaicher** [comment]
Actually nevermind. The Guzzle7 adapter supports PHP 8 already. 

If this is still relevant let me know.

**Comment by dbu** [comment]
yeah, i'd not use guzzle 6 on php 8. the composer file has the [bold statement that it supports every future php version](https://github.com/guzzle/guzzle/blob/6.5/composer.json#L24) but the last build in juli failed: https://travis-ci.org/github/guzzle/guzzle/jobs/704216007 

i guess guzzle 6 is kind of end of life anyways, guzzle 7 has been around for a while.

**Comment by dbu** [comment]
ftr: see #86

**Pull request closed without merging**
